# Generated by Django 5.0.10 on 2026-01-14 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TenantUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("owner", "Owner"), ("member", "Member")], default="member", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="tenant_users", to="core.tenant")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="tenant_users", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("tenant", "user")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="current_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="current_users",
                to="core.tenant",
            ),
        ),
    ]
