# Generated by Django 5.0.10 on 2026-01-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenant_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantuser",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("faculty", "Faculty"), ("admin", "Admin")],
                default="student",
                max_length=20,
            ),
        ),
    ]
