# Generated by Django 5.0.10 on 2026-01-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_tenantuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
